### ISSUE TITLE
[Chapter 12] 358p "application.yml 파일을 열어 비밀값으로 정의한 client-id와 client-secret, 그리고 jwt 항목을 삭제하세요." 를 진행하면 오류가 뜹니다

### ISSUE THREAD

**Issue by K-tuna** [shinsunyoung/springboot-developer#20]
![image](https://github.com/shinsunyoung/springboot-developer/assets/90139277/fe5cabbc-df5a-4686-9fad-5ad3be47df57)
처음엔 이런식으로 해보고 다음에는 저자님 깃허브 yml파일 복붙해봤는데 둘다 오류가 뜹니다.

![image](https://github.com/shinsunyoung/springboot-developer/assets/90139277/d82836d2-b8ed-41e3-88d0-1b9d2fc10d0d)
깃헙액션 오류 메세지는 이렇고

***************************
APPLICATION FAILED TO START
***************************

Description:

Method filterChain in springbootdeveloper.config.WebOAuthSecurityConfig required a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' in your configuration.

Process finished with exit code 1
저자님꺼 yml복붙하면 이런 오류가 뜹니다👆
yml 파일 안바꾸면 괜찮은데 바꾸기만 하면 오류가 뜹니다
어제 하루종일 해봤는데 모르겠네요 ㅠㅠ

**Comment by K-tuna** [comment]
깃허브 주소 안올려 드렸네요
https://github.com/dongwonkwon/myBlog

**Comment by shinsunyoung** [comment]
안녕하세요. 

```
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secret_key: secret-key
```

이 코드 그대로로 바꿔보시고 다시 시도해보시겠어요?

**Comment by K-tuna** [comment]
이렇게 하니까 바로 성공했네요! 감사합니다!
그리고 질문이 더 있는데

1. 로컬에서는 안 돌아가는게 정상이죠? 안지워야 돌아가고?
2. 그리고 jwt issuer 값은 제 이메일로 해야 되는거죠?

**Comment by shinsunyoung** [comment]
> 1. 로컬에서는 안 돌아가는게 정상이죠? 안지워야 돌아가고?

로컬에서도 저렇게 바꾸면 돌아가야합니다. 제가 예제코드를 합치다가 잘못 올라간 것 같은데 항목 자체를 지우면 안되고 의미없는 값으로 바꿔주셔야합니다. 그리고 실제로 서버에서 배포될때는 override되게 AWS에서 환경변수를 설정해줘야합니다!


> 2. 그리고 jwt issuer 값은 제 이메일로 해야 되는거죠?

넵 issuer 자체가 발행자를 의미하기 때문에 본인 이메일로 적어주시면 됩니다.

**Comment by K-tuna** [comment]
로컬에서는 값 빼면 이런식으로 401 invalid_client 오류 떠서
![image](https://github.com/shinsunyoung/springboot-developer/assets/90139277/91caa44c-5e1c-4285-907c-8c8e1881e5b3)

이런식으로 실제 유효한 값을 넣어야 돌아가더라구요
```
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 617971.....
            client-secret: GOCSPX-KV...
            scope:
              - email
              - profile
jwt:
  issuer: ehddnjs0710@gmail.com
  secret_key: secret-key
```

로컬에서는 AWS 환경변수 설정이 없으니까 유효한 값을 직접 넣어야 돌아가는게 정상인거 맞나요? 제가 이해한게 맞죠?
